import type { Doctor, Specialty, Appointment, Patient } from '@/types'

export const specialties: Specialty[] = [
  {
    id: '1',
    name: 'Tim mạch',
    slug: 'tim-mach',
    icon: 'Heart',
    description: 'Chẩn đoán và điều trị các bệnh về tim và mạch máu',
    doctorCount: 12,
  },
  {
    id: '2',
    name: 'Da liễu',
    slug: 'da-lieu',
    icon: 'Sparkles',
    description: 'Điều trị các bệnh về da, tóc và móng',
    doctorCount: 8,
  },
  {
    id: '3',
    name: 'Nhi khoa',
    slug: 'nhi-khoa',
    icon: 'Baby',
    description: 'Chăm sóc sức khỏe trẻ em từ sơ sinh đến 18 tuổi',
    doctorCount: 15,
  },
  {
    id: '4',
    name: 'Nội khoa',
    slug: 'noi-khoa',
    icon: 'Stethoscope',
    description: 'Khám và điều trị các bệnh nội khoa tổng quát',
    doctorCount: 20,
  },
  {
    id: '5',
    name: 'Thần kinh',
    slug: 'than-kinh',
    icon: 'Brain',
    description: 'Điều trị các bệnh về não và hệ thần kinh',
    doctorCount: 6,
  },
  {
    id: '6',
    name: 'Chấn thương chỉnh hình',
    slug: 'chan-thuong-chinh-hinh',
    icon: 'Bone',
    description: 'Điều trị các bệnh về xương khớp và cơ',
    doctorCount: 10,
  },
  {
    id: '7',
    name: 'Sản phụ khoa',
    slug: 'san-phu-khoa',
    icon: 'HeartPulse',
    description: 'Chăm sóc sức khỏe phụ nữ và thai sản',
    doctorCount: 14,
  },
  {
    id: '8',
    name: 'Mắt',
    slug: 'mat',
    icon: 'Eye',
    description: 'Khám và điều trị các bệnh về mắt',
    doctorCount: 7,
  },
]

export const doctors: Doctor[] = [
  {
    id: '1',
    name: 'BS. Nguyễn Văn An',
    specialty: 'Tim mạch',
    specialtySlug: 'tim-mach',
    image: '/doctors/doctor-1.jpg',
    experience: 15,
    rating: 4.9,
    reviewCount: 234,
    education: 'Tiến sĩ Y khoa - Đại học Y Hà Nội',
    bio: 'Bác sĩ Nguyễn Văn An là chuyên gia hàng đầu về tim mạch với hơn 15 năm kinh nghiệm. Ông đã điều trị thành công hàng nghìn ca bệnh phức tạp và được đồng nghiệp cũng như bệnh nhân đánh giá cao.',
    hospital: 'Bệnh viện Đa khoa Quốc tế',
    languages: ['Tiếng Việt', 'Tiếng Anh'],
    consultationFee: 500000,
    availableSlots: [
      { date: '2026-04-02', times: ['08:00', '09:00', '10:00', '14:00', '15:00'] },
      { date: '2026-04-03', times: ['08:00', '09:00', '11:00', '14:00', '16:00'] },
      { date: '2026-04-04', times: ['09:00', '10:00', '11:00', '15:00'] },
    ],
  },
  {
    id: '2',
    name: 'BS. Trần Thị Bình',
    specialty: 'Da liễu',
    specialtySlug: 'da-lieu',
    image: '/doctors/doctor-2.jpg',
    experience: 12,
    rating: 4.8,
    reviewCount: 189,
    education: 'Thạc sĩ Y khoa - Đại học Y Dược TP.HCM',
    bio: 'Bác sĩ Trần Thị Bình chuyên về da liễu thẩm mỹ và điều trị các bệnh da liễu mãn tính. Với 12 năm kinh nghiệm, bà đã giúp hàng nghìn bệnh nhân lấy lại làn da khỏe mạnh.',
    hospital: 'Bệnh viện Da liễu Trung ương',
    languages: ['Tiếng Việt', 'Tiếng Anh', 'Tiếng Pháp'],
    consultationFee: 450000,
    availableSlots: [
      { date: '2026-04-02', times: ['09:00', '10:00', '11:00', '14:00'] },
      { date: '2026-04-03', times: ['08:00', '10:00', '14:00', '15:00'] },
      { date: '2026-04-05', times: ['09:00', '10:00', '14:00', '16:00'] },
    ],
  },
  {
    id: '3',
    name: 'BS. Lê Minh Cường',
    specialty: 'Nhi khoa',
    specialtySlug: 'nhi-khoa',
    image: '/doctors/doctor-3.jpg',
    experience: 18,
    rating: 4.9,
    reviewCount: 312,
    education: 'Tiến sĩ Y khoa - Đại học Y Hà Nội',
    bio: 'Bác sĩ Lê Minh Cường là chuyên gia nhi khoa với 18 năm kinh nghiệm. Ông được biết đến với sự tận tâm và kỹ năng giao tiếp tuyệt vời với trẻ em và phụ huynh.',
    hospital: 'Bệnh viện Nhi Trung ương',
    languages: ['Tiếng Việt', 'Tiếng Anh'],
    consultationFee: 400000,
    availableSlots: [
      { date: '2026-04-02', times: ['08:00', '09:00', '10:00', '14:00', '15:00', '16:00'] },
      { date: '2026-04-03', times: ['09:00', '10:00', '11:00', '14:00'] },
      { date: '2026-04-04', times: ['08:00', '09:00', '14:00', '15:00', '16:00'] },
    ],
  },
  {
    id: '4',
    name: 'BS. Phạm Thu Hà',
    specialty: 'Nội khoa',
    specialtySlug: 'noi-khoa',
    image: '/doctors/doctor-4.jpg',
    experience: 10,
    rating: 4.7,
    reviewCount: 156,
    education: 'Thạc sĩ Y khoa - Đại học Y Dược Cần Thơ',
    bio: 'Bác sĩ Phạm Thu Hà chuyên về nội khoa tổng quát với 10 năm kinh nghiệm. Bà được bệnh nhân yêu mến bởi sự chu đáo và tận tình trong công việc.',
    hospital: 'Bệnh viện Đa khoa Quốc tế',
    languages: ['Tiếng Việt'],
    consultationFee: 350000,
    availableSlots: [
      { date: '2026-04-02', times: ['08:00', '10:00', '14:00', '15:00'] },
      { date: '2026-04-04', times: ['09:00', '10:00', '11:00', '14:00', '16:00'] },
      { date: '2026-04-05', times: ['08:00', '09:00', '10:00', '15:00'] },
    ],
  },
  {
    id: '5',
    name: 'BS. Hoàng Văn Đức',
    specialty: 'Thần kinh',
    specialtySlug: 'than-kinh',
    image: '/doctors/doctor-5.jpg',
    experience: 20,
    rating: 4.9,
    reviewCount: 278,
    education: 'Tiến sĩ Y khoa - Đại học Y Hà Nội',
    bio: 'Bác sĩ Hoàng Văn Đức là chuyên gia thần kinh hàng đầu với 20 năm kinh nghiệm. Ông đã nghiên cứu và điều trị nhiều ca bệnh phức tạp về não và hệ thần kinh.',
    hospital: 'Bệnh viện Bạch Mai',
    languages: ['Tiếng Việt', 'Tiếng Anh', 'Tiếng Đức'],
    consultationFee: 600000,
    availableSlots: [
      { date: '2026-04-03', times: ['09:00', '10:00', '14:00'] },
      { date: '2026-04-04', times: ['08:00', '09:00', '10:00', '15:00'] },
      { date: '2026-04-05', times: ['09:00', '11:00', '14:00', '15:00'] },
    ],
  },
  {
    id: '6',
    name: 'BS. Ngô Thị Lan',
    specialty: 'Sản phụ khoa',
    specialtySlug: 'san-phu-khoa',
    image: '/doctors/doctor-6.jpg',
    experience: 14,
    rating: 4.8,
    reviewCount: 245,
    education: 'Tiến sĩ Y khoa - Đại học Y Dược TP.HCM',
    bio: 'Bác sĩ Ngô Thị Lan là chuyên gia sản phụ khoa với 14 năm kinh nghiệm. Bà đã đỡ đẻ thành công hàng nghìn ca và được các bà mẹ tin tưởng.',
    hospital: 'Bệnh viện Phụ sản Trung ương',
    languages: ['Tiếng Việt', 'Tiếng Anh'],
    consultationFee: 450000,
    availableSlots: [
      { date: '2026-04-02', times: ['08:00', '09:00', '10:00', '14:00', '15:00'] },
      { date: '2026-04-03', times: ['08:00', '09:00', '14:00', '16:00'] },
      { date: '2026-04-04', times: ['09:00', '10:00', '11:00', '14:00', '15:00'] },
    ],
  },
]

export const appointments: Appointment[] = [
  {
    id: '1',
    patientName: 'Nguyễn Thị Mai',
    patientPhone: '0901234567',
    patientEmail: 'mai.nguyen@email.com',
    doctorId: '1',
    doctorName: 'BS. Nguyễn Văn An',
    specialty: { name: 'Tim mạch' },
    date: '2026-04-02',
    time: '09:00',
    status: 'confirmed',
    notes: 'Tái khám sau 2 tuần điều trị',
    createdAt: '2026-03-28T10:30:00Z',
  },
  {
    id: '2',
    patientName: 'Trần Văn Bảo',
    patientPhone: '0912345678',
    patientEmail: 'bao.tran@email.com',
    doctorId: '3',
    doctorName: 'BS. Lê Minh Cường',
    specialty: { name: 'Nhi khoa' },
    date: '2026-04-02',
    time: '10:00',
    status: 'pending',
    notes: 'Khám sức khỏe định kỳ cho con',
    createdAt: '2026-03-29T14:20:00Z',
  },
  {
    id: '3',
    patientName: 'Lê Thị Hương',
    patientPhone: '0923456789',
    patientEmail: 'huong.le@email.com',
    doctorId: '2',
    doctorName: 'BS. Trần Thị Bình',
    specialty: { name: 'Da liễu' },
    date: '2026-04-03',
    time: '14:00',
    status: 'confirmed',
    createdAt: '2026-03-30T09:15:00Z',
  },
  {
    id: '4',
    patientName: 'Phạm Minh Tuấn',
    patientPhone: '0934567890',
    patientEmail: 'tuan.pham@email.com',
    doctorId: '5',
    doctorName: 'BS. Hoàng Văn Đức',
    specialty: { name: 'Thần kinh' },
    date: '2026-04-01',
    time: '09:00',
    status: 'completed',
    notes: 'Đau đầu kéo dài',
    createdAt: '2026-03-25T11:00:00Z',
  },
  {
    id: '5',
    patientName: 'Võ Thị Kim',
    patientPhone: '0945678901',
    patientEmail: 'kim.vo@email.com',
    doctorId: '6',
    doctorName: 'BS. Ngô Thị Lan',
    specialty: { name: 'Sản phụ khoa' },
    date: '2026-04-04',
    time: '08:00',
    status: 'pending',
    notes: 'Khám thai định kỳ',
    createdAt: '2026-03-31T08:45:00Z',
  },
]

export const patients: Patient[] = [
  {
    id: '1',
    name: 'Nguyễn Thị Mai',
    email: 'mai.nguyen@email.com',
    phone: '0901234567',
    dateOfBirth: '1985-06-15',
    gender: 'FEMALE',
    address: '123 Đường Lê Lợi, Quận 1, TP.HCM',
    appointmentCount: 5,
    lastVisit: '2026-03-15',
  },
  {
    id: '2',
    name: 'Trần Văn Bảo',
    email: 'bao.tran@email.com',
    phone: '0912345678',
    dateOfBirth: '1990-03-22',
    gender: 'MALE',
    address: '456 Đường Nguyễn Huệ, Quận 3, TP.HCM',
    appointmentCount: 3,
    lastVisit: '2026-03-20',
  },
  {
    id: '3',
    name: 'Lê Thị Hương',
    email: 'huong.le@email.com',
    phone: '0923456789',
    dateOfBirth: '1978-11-08',
    gender: 'FEMALE',
    address: '789 Đường Trần Hưng Đạo, Quận 5, TP.HCM',
    appointmentCount: 8,
    lastVisit: '2026-03-28',
  },
  {
    id: '4',
    name: 'Phạm Minh Tuấn',
    email: 'tuan.pham@email.com',
    phone: '0934567890',
    dateOfBirth: '1982-09-30',
    gender: 'MALE',
    address: '321 Đường Võ Văn Tần, Quận 3, TP.HCM',
    appointmentCount: 2,
    lastVisit: '2026-04-01',
  },
  {
    id: '5',
    name: 'Võ Thị Kim',
    email: 'kim.vo@email.com',
    phone: '0945678901',
    dateOfBirth: '1995-01-12',
    gender: 'FEMALE',
    address: '654 Đường Điện Biên Phủ, Quận Bình Thạnh, TP.HCM',
    appointmentCount: 4,
    lastVisit: '2026-03-25',
  },
]

export const testimonials = [
  {
    id: '1',
    name: 'Nguyễn Thị Lan',
    avatar: '/avatars/avatar-1.jpg',
    rating: 5,
    content: 'Dịch vụ tuyệt vời! Bác sĩ rất tận tâm và chuyên nghiệp. Tôi rất hài lòng với trải nghiệm khám bệnh tại đây.',
    date: '2026-03-20',
  },
  {
    id: '2',
    name: 'Trần Văn Minh',
    avatar: '/avatars/avatar-2.jpg',
    rating: 5,
    content: 'Đặt lịch online rất tiện lợi, không phải chờ đợi lâu. Sẽ quay lại và giới thiệu cho bạn bè.',
    date: '2026-03-18',
  },
  {
    id: '3',
    name: 'Lê Hoàng Anh',
    avatar: '/avatars/avatar-3.jpg',
    rating: 4,
    content: 'Cơ sở vật chất hiện đại, nhân viên thân thiện. Quy trình khám bệnh rõ ràng và nhanh chóng.',
    date: '2026-03-15',
  },
]

export const stats = {
  totalDoctors: 85,
  totalPatients: 15000,
  totalAppointments: 50000,
  satisfactionRate: 98,
}

export const monthlyPatientData = [
  { month: 'Tháng 1', patients: 1200 },
  { month: 'Tháng 2', patients: 1450 },
  { month: 'Tháng 3', patients: 1680 },
  { month: 'Tháng 4', patients: 1920 },
  { month: 'Tháng 5', patients: 2150 },
  { month: 'Tháng 6', patients: 2340 },
  { month: 'Tháng 7', patients: 2580 },
  { month: 'Tháng 8', patients: 2890 },
  { month: 'Tháng 9', patients: 3120 },
  { month: 'Tháng 10', patients: 3450 },
  { month: 'Tháng 11', patients: 3680 },
  { month: 'Tháng 12', patients: 3920 },
]

export const patientsBySpecialty = [
  { specialty: 'Nội khoa', patients: 2450, fill: 'hsl(var(--chart-1))' },
  { specialty: 'Tim mạch', patients: 1680, fill: 'hsl(var(--chart-2))' },
  { specialty: 'Nhi khoa', patients: 1920, fill: 'hsl(var(--chart-3))' },
  { specialty: 'Sản phụ khoa', patients: 1450, fill: 'hsl(var(--chart-4))' },
  { specialty: 'Da liễu', patients: 980, fill: 'hsl(var(--chart-5))' },
  { specialty: 'Chấn thương chỉnh hình', patients: 1120, fill: 'hsl(var(--chart-1))' },
  { specialty: 'Thần kinh', patients: 850, fill: 'hsl(var(--chart-2))' },
  { specialty: 'Mắt', patients: 680, fill: 'hsl(var(--chart-3))' },
]
